name: light_im_uikit
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  light_im_sdk:
    path: ../light-im-sdk
  cross_file: ^0.3.3+4
  extended_image: ^8.0.2
  extended_text_field: ^12.0.1
  fc_native_video_thumbnail: ^0.5.2
  file_selector: ^1.0.0
  flutter_slidable: ^3.0.0
  media_kit: ^1.1.3+1
  media_kit_native_event_loop: ^1.0.7
  media_kit_video: ^1.1.3
  media_kit_libs_android_video: ^1.3.1
  media_kit_libs_ios_video: ^1.1.2
  media_kit_libs_macos_video: ^1.1.2
  media_kit_libs_windows_video: ^1.0.6
  media_kit_libs_linux: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.1.0
  provider: ^6.0.5
  record: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1


flutter:
  assets:
    - assets/emoticon/


flutter_gen:
  output: lib/src/assets/
