name: light_im_uikit
description: A light im.
version: 0.1.1
repository: https://github.com/ggdream/light-im-uikit
publish_to: none
environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # light_im_sdk: ^0.1.0
  light_im_sdk:
    path: ../light-im-sdk
  cross_file: ^0.3.3+8
  device_info_plus: ^9.1.2
  extended_image: ^8.2.0
  extended_text_field: ^14.0.0
  fc_native_video_thumbnail: ^0.8.0
  file_selector: ^1.0.3
  flutter_slidable: ^3.0.1
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  provider: ^6.1.1
  record: ^4.4.4
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0


flutter:
  assets:
    - assets/emoticon/


flutter_gen:
  output: lib/src/assets/
